export const main_data = [
    {
        id: 0,
        group: 1, // 1은 이대 정문
        name: "모미지식당",
        category: "한식",
        address: "서울 서대문구 이화여대7길 24 2층",
        business_hours: "11 : 00 - 22 : 00 / 21 : 00 (라스트 오더)",
        detail_address: "신촌역 1번 출구에서 238m",
        parking: "주차 불가능",
        menu_1: "육회덮밥",
        menu_1_price: "10,000원",
        menu_2: "소고기가지덮밥",
        menu_2_price: "8,500원",
    },
    {
        id: 1,
        group: 1,
        name: "유야케도쿄",
        category: "돈가스",
        star: "4.7",
        address: "서울 서대문구 이화여대3길 28 101호",
        detail_address: "이대역1번 출구에서 256m",
        business_hours: "11 : 30 - 21 : 00",
        parking: "주차 불가능",
        menu_1: "등심돈가스",
        menu_1_price: "9,000원",
        menu_2: "안심돈가스",
        menu_2_price: "10,500원",
        menu_3: "치즈돈가스",
        menu_3_price: "10,500원",
    },
    {
        id: 2,
        group: 1,
        name: "원즈오운",
        category: "베이커리",
        address: "서울 서대문구 이화여대길 20 1층",
        business_hours: "10 : 00 - 21 : 00 / 20 : 30 (라스트 오더)",
        detail_address: "이대역 3번 출구에서 76m",
        parking: "주차 불가능",
        menu_1: "잠봉뵈르",
        menu_1_price: "8,900원",
        menu_2: "사과 콩포트 브리치즈 바게트",
        menu_2_price: "8,500원",
        menu_3: "스모크드 베이컨 할라피뇨 바게트",
        menu_3_price: "8,900원",
    },
    {
        id: 3,
        group: 2, // 2는 이대 후문
        name: "스탠바이키친",
        category: "샌드위치",
        address: "서울 서대문구 연대동문길 49",
        business_hours: "10 : 30 - 20 : 30 / 15 : 00 - 16 : 00 (브레이크 타임)",
        detail_address: "신촌역 2번 출구에서 679m",
        parking: "주차 불가능",
        menu_1: "베이컨 양상추 토마토",
        menu_1_price: "6,800원",
        menu_2: "베트남 치킨 반미",
        menu_2_price: "7,300원",
        menu_3: "베이컨 치즈 오믈렛",
        menu_3_price: "7,800원",
    },
    {
        id: 4,
        group: 2,
        name: "로드샌드위치",
        category: "양식",
        address: "서울 서대문구 연대동문길 45 1층 로드샌드위치",
        business_hours: "10 : 30 - 20 : 00 / 15 : 30 - 17 : 00 (브레이크 타임)",
        detail_address: "신촌역 2번 출구에서 654m",
        parking: "주차 불가능",
        menu_1: "비엘티 샌드위치",
        menu_1_price: "10,000원",
        menu_2: "감베리 샌드위치",
        menu_2_price: "11,000원",
        menu_3: "연어 샌드위치",
        menu_3_price: "11,00원",
    },
    {
        id: 5,
        group: 2,
        name: "딸기골",
        category: "종합분식",
        address: "서울 서대문구 연대동문길 29",
        business_hours: "07 : 00 - 21 : 30",
        detail_address: "신촌역 2번 출구에서 582m",
        parking: "주차 불가능",
        menu_1: "치즈 김치 순두부",
        menu_1_price: "5,500원",
        menu_2: "돌솥비빔밥",
        menu_2_price: "5,500원",
        menu_3: "김치찌개",
        menu_3_price: "5,000원",
    },
    {
        id: 6,
        group: 3, // 3은 신촌
        name: "정육면체",
        category: "아시아 음식",
        address: "서울 서대문구 연세로5다길 22-8 1층 정육면체",
        business_hours: "11 : 30 - 21 : 00",
        detail_address: "신촌역 1번 출구에서 301m",
        parking: "주차 불가능",
        menu_1: "홍탄",
        menu_1_price: "10,000원",
        menu_2: "깨부수면",
        menu_2_price: "12,000원",
        menu_3: "마라새우면",
        menu_3_price: "12,000원",
    },
    {
        id: 7,
        group: 3,
        name: "정통집",
        category: "돼지고기구이",
        address: "서울 서대문구 연세로9길 7 1층",
        business_hours: "11 : 00 - 23 : 00",
        detail_address: "신촌역 2번 출구에서 358m",
        parking: "주차 불가능",
        menu_1: "돼지김치구이(소)",
        menu_1_price: "24,000원",
        menu_2: "돼지김치구이(중)",
        menu_2_price: "29,000원",
        menu_3: "특미볶음밥",
        menu_3_price: "2,500원",
    },
    {
        id: 8,
        group: 3,
        name: "돈부리모노",
        category: "일식당",
        address: "서울 서대문구 연세로4길 46 1층",
        business_hours: "11 : 30 - 21 : 30 / 15 : 00 - 16 : 00 (브레이크 타임)",
        detail_address: "신촌역 4번 출구에서 388m",
        parking: "주차 불가능",
        menu_1: "김치치즈가츠동",
        menu_1_price: "8,000원",
        menu_2: "부타동",
        menu_2_price: "8,500원",
        menu_3: "사케동",
        menu_3_price: "11,000원",
    },
]
